name = "Hippocampal Pain"
author = "Balvenie"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aca9b07f3843869f38346b02f6a80969a09e855913e3b0d3c1a0b642a98230b2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
