#Range: 0 ~ 100
deathPenaltyMin = 0
#Range: 0 ~ 100
deathPenaltyLoss = 100
#Allowed Values: AMOUNT, PERCENT, RESET
deathPenaltyMethod = "AMOUNT"
#Range: 0 ~ 100
gainPenaltyPerGroup = 15
#Range: 0 ~ 100
decayPenaltyPerGroup = 15
foodOverrides = []
generateGroupsForEmptyItems = true
hideTooltipsUntilEaten = false
