#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 26 13:25:43 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
